# Generated by Django 5.2.16 on 2026-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workingset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('sv', 'Swedish'), ('nl', 'Dutch')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('sv', 'Swedish'), ('nl', 'Dutch')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workingset',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('sv', 'Swedish'), ('nl', 'Dutch')], max_length=10),
        ),
    ]
