export PATH := "venv/bin:" + env_var("PATH")

run: db-up migrate
    python manage.py runserver

db-up:
    docker compose up -d

db-down:
    docker compose down

migrate:
    python manage.py migrate
