# Generated by Django 5.2.16 on 2026-07-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('article', 'Article'), ('interjection', 'Interjection'), ('other', 'Other')], max_length=20)),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('sv', 'Swedish'), ('nl', 'Dutch')], max_length=10)),
                ('translation', models.CharField(help_text='English translation of the word.', max_length=100)),
            ],
            options={
                'ordering': ['language', 'category', 'text'],
            },
        ),
    ]
