# Generated by Django 5.2.16 on 2026-07-10 21:17

from django.db import migrations

WORDS = [
    ('el', 'article', 'the'),
    ('la', 'article', 'the'),
    ('gato', 'noun', 'cat'),
    ('perro', 'noun', 'dog'),
    ('correr', 'verb', 'run'),
    ('comer', 'verb', 'eat'),
    ('saltar', 'verb', 'jump'),
    ('feliz', 'adjective', 'happy'),
    ('grande', 'adjective', 'big'),
    ('rápidamente', 'adverb', 'quickly'),
    ('ella', 'pronoun', 'she'),
    ('él', 'pronoun', 'he'),
    ('en', 'preposition', 'on'),
    ('y', 'conjunction', 'and'),
]


def seed_words(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.bulk_create(
        Word(text=text, category=category, language='es', translation=translation)
        for text, category, translation in WORDS
    )


def unseed_words(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.filter(
        text__in=[w[0] for w in WORDS],
        language='es',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_words, unseed_words),
    ]
