# Generated by Django 5.2.16 on 2026-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_seed_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('article', 'Article'), ('interjection', 'Interjection'), ('prefix', 'Prefix'), ('suffix', 'Suffix'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, help_text='English translation of the word, if any.', max_length=100, null=True),
        ),
    ]
