# Generated by Django 5.2.16 on 2026-07-11 21:21

from django.db import migrations

WORD_PARTS = [
    ('des-', 'prefix'),
    ('re-', 'prefix'),
    ('in-', 'prefix'),
    ('-mente', 'suffix'),
    ('-ito', 'suffix'),
    ('-ción', 'suffix'),
]


def seed_word_parts(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.bulk_create(
        Word(text=text, category=category, language='es', translation=None)
        for text, category in WORD_PARTS
    )


def unseed_word_parts(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.filter(
        text__in=[w[0] for w in WORD_PARTS],
        language='es',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_category_alter_word_translation'),
    ]

    operations = [
        migrations.RunPython(seed_word_parts, unseed_word_parts),
    ]
