from django.db import migrations, models

# (text, category, language, translation)
VOCABULARY = [
    ('jabłko', 'noun', 'pl', 'apple'),
    ('äpple', 'noun', 'sv', 'apple'),
    ('pomme', 'noun', 'fr', 'apple'),
    ('apfel', 'noun', 'de', 'apple'),
    ('appel', 'noun', 'nl', 'apple'),
    ('chłopiec', 'noun', 'pl', 'boy'),
    ('pojke', 'noun', 'sv', 'boy'),
    ('garçon', 'noun', 'fr', 'boy'),
    ('junge', 'noun', 'de', 'boy'),
    ('jongen', 'noun', 'nl', 'boy'),
    ('dziewczyna', 'noun', 'pl', 'girl'),
    ('flicka', 'noun', 'sv', 'girl'),
    ('fille', 'noun', 'fr', 'girl'),
    ('mädchen', 'noun', 'de', 'girl'),
    ('meisje', 'noun', 'nl', 'girl'),
    ('mężczyzna', 'noun', 'pl', 'man'),
    ('man', 'noun', 'sv', 'man'),
    ('homme', 'noun', 'fr', 'man'),
    ('mann', 'noun', 'de', 'man'),
    ('man', 'noun', 'nl', 'man'),
    ('kobieta', 'noun', 'pl', 'woman'),
    ('kvinna', 'noun', 'sv', 'woman'),
    ('femme', 'noun', 'fr', 'woman'),
    ('frau', 'noun', 'de', 'woman'),
    ('vrouw', 'noun', 'nl', 'woman'),
    ('woda', 'noun', 'pl', 'water'),
    ('vatten', 'noun', 'sv', 'water'),
    ('eau', 'noun', 'fr', 'water'),
    ('wasser', 'noun', 'de', 'water'),
    ('water', 'noun', 'nl', 'water'),
    ('chleb', 'noun', 'pl', 'bread'),
    ('bröd', 'noun', 'sv', 'bread'),
    ('pain', 'noun', 'fr', 'bread'),
    ('brot', 'noun', 'de', 'bread'),
    ('brood', 'noun', 'nl', 'bread'),
    ('pies', 'noun', 'pl', 'dog'),
    ('hund', 'noun', 'sv', 'dog'),
    ('chien', 'noun', 'fr', 'dog'),
    ('hund', 'noun', 'de', 'dog'),
    ('hond', 'noun', 'nl', 'dog'),
    ('kot', 'noun', 'pl', 'cat'),
    ('katt', 'noun', 'sv', 'cat'),
    ('chat', 'noun', 'fr', 'cat'),
    ('katze', 'noun', 'de', 'cat'),
    ('kat', 'noun', 'nl', 'cat'),
    ('dom', 'noun', 'pl', 'house'),
    ('hus', 'noun', 'sv', 'house'),
    ('maison', 'noun', 'fr', 'house'),
    ('haus', 'noun', 'de', 'house'),
    ('huis', 'noun', 'nl', 'house'),
    ('książka', 'noun', 'pl', 'book'),
    ('bok', 'noun', 'sv', 'book'),
    ('livre', 'noun', 'fr', 'book'),
    ('buch', 'noun', 'de', 'book'),
    ('boek', 'noun', 'nl', 'book'),
    ('samochód', 'noun', 'pl', 'car'),
    ('bil', 'noun', 'sv', 'car'),
    ('voiture', 'noun', 'fr', 'car'),
    ('auto', 'noun', 'de', 'car'),
    ('auto', 'noun', 'nl', 'car'),
    ('kawa', 'noun', 'pl', 'coffee'),
    ('kaffe', 'noun', 'sv', 'coffee'),
    ('café', 'noun', 'fr', 'coffee'),
    ('Kaffee', 'noun', 'de', 'coffee'),
    ('koffie', 'noun', 'nl', 'coffee'),
    ('herbata', 'noun', 'pl', 'tea'),
    ('te', 'noun', 'sv', 'tea'),
    ('thé', 'noun', 'fr', 'tea'),
    ('Tee', 'noun', 'de', 'tea'),
    ('thee', 'noun', 'nl', 'tea'),
    ('wegetarianin', 'noun', 'pl', 'vegetarian'),
    ('vegetarian', 'noun', 'sv', 'vegetarian'),
    ('végétarien', 'noun', 'fr', 'vegetarian'),
    ('Vegetarier', 'noun', 'de', 'vegetarian'),
    ('vegetariër', 'noun', 'nl', 'vegetarian'),
    ('weganin', 'noun', 'pl', 'vegan'),
    ('vegan', 'noun', 'sv', 'vegan'),
    ('végan', 'noun', 'fr', 'vegan'),
    ('Veganer', 'noun', 'de', 'vegan'),
    ('veganist', 'noun', 'nl', 'vegan'),
    ('mleko', 'noun', 'pl', 'milk'),
    ('mjölk', 'noun', 'sv', 'milk'),
    ('lait', 'noun', 'fr', 'milk'),
    ('Milch', 'noun', 'de', 'milk'),
    ('melk', 'noun', 'nl', 'milk'),
    ('orzechy', 'noun', 'pl', 'nuts'),
    ('nötter', 'noun', 'sv', 'nuts'),
    ('noix', 'noun', 'fr', 'nuts'),
    ('Nüsse', 'noun', 'de', 'nuts'),
    ('noten', 'noun', 'nl', 'nuts'),
    ('kiwi', 'noun', 'pl', 'kiwi'),
    ('kiwi', 'noun', 'sv', 'kiwi'),
    ('kiwi', 'noun', 'fr', 'kiwi'),
    ('Kiwi', 'noun', 'de', 'kiwi'),
    ('kiwi', 'noun', 'nl', 'kiwi'),
    ('kurczak', 'noun', 'pl', 'chicken'),
    ('kyckling', 'noun', 'sv', 'chicken'),
    ('poulet', 'noun', 'fr', 'chicken'),
    ('Hähnchen', 'noun', 'de', 'chicken'),
    ('kip', 'noun', 'nl', 'chicken'),
    ('wołowina', 'noun', 'pl', 'beef'),
    ('nötkött', 'noun', 'sv', 'beef'),
    ('bœuf', 'noun', 'fr', 'beef'),
    ('Rindfleisch', 'noun', 'de', 'beef'),
    ('rundvlees', 'noun', 'nl', 'beef'),
    ('mięso', 'noun', 'pl', 'meat'),
    ('kött', 'noun', 'sv', 'meat'),
    ('viande', 'noun', 'fr', 'meat'),
    ('Fleisch', 'noun', 'de', 'meat'),
    ('vlees', 'noun', 'nl', 'meat'),
    ('ryba', 'noun', 'pl', 'fish'),
    ('fisk', 'noun', 'sv', 'fish'),
    ('poisson', 'noun', 'fr', 'fish'),
    ('Fisch', 'noun', 'de', 'fish'),
    ('vis', 'noun', 'nl', 'fish'),
    ('jeść', 'verb', 'pl', 'eat'),
    ('äta', 'verb', 'sv', 'eat'),
    ('manger', 'verb', 'fr', 'eat'),
    ('essen', 'verb', 'de', 'eat'),
    ('eten', 'verb', 'nl', 'eat'),
    ('pić', 'verb', 'pl', 'drink'),
    ('dricka', 'verb', 'sv', 'drink'),
    ('boire', 'verb', 'fr', 'drink'),
    ('trinken', 'verb', 'de', 'drink'),
    ('drinken', 'verb', 'nl', 'drink'),
    ('biegać', 'verb', 'pl', 'run'),
    ('springa', 'verb', 'sv', 'run'),
    ('courir', 'verb', 'fr', 'run'),
    ('rennen', 'verb', 'de', 'run'),
    ('rennen', 'verb', 'nl', 'run'),
    ('czytać', 'verb', 'pl', 'read'),
    ('läsa', 'verb', 'sv', 'read'),
    ('lire', 'verb', 'fr', 'read'),
    ('lesen', 'verb', 'de', 'read'),
    ('lezen', 'verb', 'nl', 'read'),
    ('spać', 'verb', 'pl', 'sleep'),
    ('sova', 'verb', 'sv', 'sleep'),
    ('dormir', 'verb', 'fr', 'sleep'),
    ('schlafen', 'verb', 'de', 'sleep'),
    ('slapen', 'verb', 'nl', 'sleep'),
    ('mieć', 'verb', 'pl', 'have'),
    ('ha', 'verb', 'sv', 'have'),
    ('avoir', 'verb', 'fr', 'have'),
    ('haben', 'verb', 'de', 'have'),
    ('hebben', 'verb', 'nl', 'have'),
    ('lubić', 'verb', 'pl', 'like'),
    ('gilla', 'verb', 'sv', 'like'),
    ('aimer', 'verb', 'fr', 'like'),
    ('mögen', 'verb', 'de', 'like'),
    ('leuk vinden', 'verb', 'nl', 'like'),
    ('być', 'verb', 'pl', 'be'),
    ('vara', 'verb', 'sv', 'be'),
    ('être', 'verb', 'fr', 'be'),
    ('sein', 'verb', 'de', 'be'),
    ('zijn', 'verb', 'nl', 'be'),
    ('iść', 'verb', 'pl', 'go'),
    ('gå', 'verb', 'sv', 'go'),
    ('aller', 'verb', 'fr', 'go'),
    ('gehen', 'verb', 'de', 'go'),
    ('gaan', 'verb', 'nl', 'go'),
    ('robić', 'verb', 'pl', 'do'),
    ('göra', 'verb', 'sv', 'do'),
    ('faire', 'verb', 'fr', 'do'),
    ('tun', 'verb', 'de', 'do'),
    ('doen', 'verb', 'nl', 'do'),
    ('robić', 'verb', 'pl', 'make'),
    ('göra', 'verb', 'sv', 'make'),
    ('faire', 'verb', 'fr', 'make'),
    ('machen', 'verb', 'de', 'make'),
    ('maken', 'verb', 'nl', 'make'),
    ('wiedzieć', 'verb', 'pl', 'know'),
    ('veta', 'verb', 'sv', 'know'),
    ('savoir', 'verb', 'fr', 'know'),
    ('wissen', 'verb', 'de', 'know'),
    ('weten', 'verb', 'nl', 'know'),
    ('myśleć', 'verb', 'pl', 'think'),
    ('tänka', 'verb', 'sv', 'think'),
    ('penser', 'verb', 'fr', 'think'),
    ('denken', 'verb', 'de', 'think'),
    ('denken', 'verb', 'nl', 'think'),
    ('brać', 'verb', 'pl', 'take'),
    ('ta', 'verb', 'sv', 'take'),
    ('prendre', 'verb', 'fr', 'take'),
    ('nehmen', 'verb', 'de', 'take'),
    ('nemen', 'verb', 'nl', 'take'),
    ('widzieć', 'verb', 'pl', 'see'),
    ('se', 'verb', 'sv', 'see'),
    ('voir', 'verb', 'fr', 'see'),
    ('sehen', 'verb', 'de', 'see'),
    ('zien', 'verb', 'nl', 'see'),
    ('przychodzić', 'verb', 'pl', 'come'),
    ('komma', 'verb', 'sv', 'come'),
    ('venir', 'verb', 'fr', 'come'),
    ('kommen', 'verb', 'de', 'come'),
    ('komen', 'verb', 'nl', 'come'),
    ('chcieć', 'verb', 'pl', 'want'),
    ('vilja', 'verb', 'sv', 'want'),
    ('vouloir', 'verb', 'fr', 'want'),
    ('wollen', 'verb', 'de', 'want'),
    ('willen', 'verb', 'nl', 'want'),
    ('używać', 'verb', 'pl', 'use'),
    ('använda', 'verb', 'sv', 'use'),
    ('utiliser', 'verb', 'fr', 'use'),
    ('benutzen', 'verb', 'de', 'use'),
    ('gebruiken', 'verb', 'nl', 'use'),
    ('znaleźć', 'verb', 'pl', 'find'),
    ('hitta', 'verb', 'sv', 'find'),
    ('trouver', 'verb', 'fr', 'find'),
    ('finden', 'verb', 'de', 'find'),
    ('vinden', 'verb', 'nl', 'find'),
    ('kochać', 'verb', 'pl', 'love'),
    ('älska', 'verb', 'sv', 'love'),
    ('aimer', 'verb', 'fr', 'love'),
    ('lieben', 'verb', 'de', 'love'),
    ('houden van', 'verb', 'nl', 'love'),
    ('nie', 'operators', 'pl', 'not'),
    ('inte', 'operators', 'sv', 'not'),
    ('ne pas', 'operators', 'fr', 'not'),
    ('nicht', 'operators', 'de', 'not'),
    ('niet', 'operators', 'nl', 'not'),
    ('i', 'operators', 'pl', 'and'),
    ('och', 'operators', 'sv', 'and'),
    ('et', 'operators', 'fr', 'and'),
    ('und', 'operators', 'de', 'and'),
    ('en', 'operators', 'nl', 'and'),
    ('ale', 'operators', 'pl', 'but'),
    ('men', 'operators', 'sv', 'but'),
    ('mais', 'operators', 'fr', 'but'),
    ('aber', 'operators', 'de', 'but'),
    ('maar', 'operators', 'nl', 'but'),
    ('albo', 'operators', 'pl', 'or'),
    ('eller', 'operators', 'sv', 'or'),
    ('ou', 'operators', 'fr', 'or'),
    ('oder', 'operators', 'de', 'or'),
    ('of', 'operators', 'nl', 'or'),
    ('ponieważ', 'operators', 'pl', 'because'),
    ('eftersom', 'operators', 'sv', 'because'),
    ('parce que', 'operators', 'fr', 'because'),
    ('weil', 'operators', 'de', 'because'),
    ('omdat', 'operators', 'nl', 'because'),
    ('jeśli', 'operators', 'pl', 'if'),
    ('om', 'operators', 'sv', 'if'),
    ('si', 'operators', 'fr', 'if'),
    ('wenn', 'operators', 'de', 'if'),
    ('als', 'operators', 'nl', 'if'),
    ('cześć', 'actants', 'pl', 'hello'),
    ('hej', 'actants', 'sv', 'hello'),
    ('bonjour', 'actants', 'fr', 'hello'),
    ('hallo', 'actants', 'de', 'hello'),
    ('hallo', 'actants', 'nl', 'hello'),
    ('do widzenia', 'actants', 'pl', 'goodbye'),
    ('hejdå', 'actants', 'sv', 'goodbye'),
    ('au revoir', 'actants', 'fr', 'goodbye'),
    ('tschüss', 'actants', 'de', 'goodbye'),
    ('tot ziens', 'actants', 'nl', 'goodbye'),
    ('proszę', 'actants', 'pl', 'please'),
    ('snälla', 'actants', 'sv', 'please'),
    ('s\'il vous plaît', 'actants', 'fr', 'please'),
    ('bitte', 'actants', 'de', 'please'),
    ('alsjeblieft', 'actants', 'nl', 'please'),
    ('dziękuję', 'actants', 'pl', 'thanks'),
    ('tack', 'actants', 'sv', 'thanks'),
    ('merci', 'actants', 'fr', 'thanks'),
    ('danke', 'actants', 'de', 'thanks'),
    ('bedankt', 'actants', 'nl', 'thanks'),
    ('w', 'relators', 'pl', 'in'),
    ('i', 'relators', 'sv', 'in'),
    ('dans', 'relators', 'fr', 'in'),
    ('in', 'relators', 'de', 'in'),
    ('in', 'relators', 'nl', 'in'),
    ('na', 'relators', 'pl', 'on'),
    ('på', 'relators', 'sv', 'on'),
    ('sur', 'relators', 'fr', 'on'),
    ('auf', 'relators', 'de', 'on'),
    ('op', 'relators', 'nl', 'on'),
    ('przy', 'relators', 'pl', 'at'),
    ('vid', 'relators', 'sv', 'at'),
    ('à', 'relators', 'fr', 'at'),
    ('an', 'relators', 'de', 'at'),
    ('bij', 'relators', 'nl', 'at'),
    ('pod', 'relators', 'pl', 'under'),
    ('under', 'relators', 'sv', 'under'),
    ('sous', 'relators', 'fr', 'under'),
    ('unter', 'relators', 'de', 'under'),
    ('onder', 'relators', 'nl', 'under'),
    ('z', 'relators', 'pl', 'with'),
    ('med', 'relators', 'sv', 'with'),
    ('avec', 'relators', 'fr', 'with'),
    ('mit', 'relators', 'de', 'with'),
    ('met', 'relators', 'nl', 'with'),
    ('od', 'relators', 'pl', 'from'),
    ('från', 'relators', 'sv', 'from'),
    ('de', 'relators', 'fr', 'from'),
    ('von', 'relators', 'de', 'from'),
    ('van', 'relators', 'nl', 'from'),
    ('do', 'relators', 'pl', 'to'),
    ('till', 'relators', 'sv', 'to'),
    ('à', 'relators', 'fr', 'to'),
    ('zu', 'relators', 'de', 'to'),
    ('naar', 'relators', 'nl', 'to'),
    ('z', 'relators', 'pl', 'of'),
    ('av', 'relators', 'sv', 'of'),
    ('de', 'relators', 'fr', 'of'),
    ('von', 'relators', 'de', 'of'),
    ('van', 'relators', 'nl', 'of'),
    ('bez', 'relators', 'pl', 'without'),
    ('utan', 'relators', 'sv', 'without'),
    ('sans', 'relators', 'fr', 'without'),
    ('ohne', 'relators', 'de', 'without'),
    ('zonder', 'relators', 'nl', 'without'),
    ('dla', 'relators', 'pl', 'for'),
    ('för', 'relators', 'sv', 'for'),
    ('pour', 'relators', 'fr', 'for'),
    ('für', 'relators', 'de', 'for'),
    ('voor', 'relators', 'nl', 'for'),
    ('my', 'actants', 'pl', 'we'),
    ('vi', 'actants', 'sv', 'we'),
    ('nous', 'actants', 'fr', 'we'),
    ('wir', 'actants', 'de', 'we'),
    ('wij', 'actants', 'nl', 'we'),
    ('oni', 'actants', 'pl', 'they'),
    ('de', 'actants', 'sv', 'they'),
    ('ils', 'actants', 'fr', 'they'),
    ('sie', 'actants', 'de', 'they'),
    ('zij', 'actants', 'nl', 'they'),
    ('mnie', 'actants', 'pl', 'me'),
    ('mig', 'actants', 'sv', 'me'),
    ('me', 'actants', 'fr', 'me'),
    ('mich', 'actants', 'de', 'me'),
    ('mij', 'actants', 'nl', 'me'),
    ('jego', 'actants', 'pl', 'him'),
    ('honom', 'actants', 'sv', 'him'),
    ('le', 'actants', 'fr', 'him'),
    ('ihn', 'actants', 'de', 'him'),
    ('hem', 'actants', 'nl', 'him'),
    ('jej', 'actants', 'pl', 'her'),
    ('henne', 'actants', 'sv', 'her'),
    ('la', 'actants', 'fr', 'her'),
    ('sie', 'actants', 'de', 'her'),
    ('haar', 'actants', 'nl', 'her'),
    ('nas', 'actants', 'pl', 'us'),
    ('oss', 'actants', 'sv', 'us'),
    ('nous', 'actants', 'fr', 'us'),
    ('uns', 'actants', 'de', 'us'),
    ('ons', 'actants', 'nl', 'us'),
    ('ich', 'actants', 'pl', 'them'),
    ('dem', 'actants', 'sv', 'them'),
    ('les', 'actants', 'fr', 'them'),
    ('sie', 'actants', 'de', 'them'),
    ('hen', 'actants', 'nl', 'them'),
    ('mój', 'actants', 'pl', 'my'),
    ('min', 'actants', 'sv', 'my'),
    ('mon', 'actants', 'fr', 'my'),
    ('mein', 'actants', 'de', 'my'),
    ('mijn', 'actants', 'nl', 'my'),
    ('twój', 'actants', 'pl', 'your'),
    ('din', 'actants', 'sv', 'your'),
    ('ton', 'actants', 'fr', 'your'),
    ('dein', 'actants', 'de', 'your'),
    ('jouw', 'actants', 'nl', 'your'),
    ('jego', 'actants', 'pl', 'his'),
    ('hans', 'actants', 'sv', 'his'),
    ('son', 'actants', 'fr', 'his'),
    ('sein', 'actants', 'de', 'his'),
    ('zijn', 'actants', 'nl', 'his'),
    ('nasz', 'actants', 'pl', 'our'),
    ('vår', 'actants', 'sv', 'our'),
    ('notre', 'actants', 'fr', 'our'),
    ('unser', 'actants', 'de', 'our'),
    ('ons', 'actants', 'nl', 'our'),
    ('ich', 'actants', 'pl', 'their'),
    ('deras', 'actants', 'sv', 'their'),
    ('leur', 'actants', 'fr', 'their'),
    ('ihr', 'actants', 'de', 'their'),
    ('hun', 'actants', 'nl', 'their'),
    ('ten', 'actants', 'pl', 'this'),
    ('den här', 'actants', 'sv', 'this'),
    ('ce', 'actants', 'fr', 'this'),
    ('dies', 'actants', 'de', 'this'),
    ('dit', 'actants', 'nl', 'this'),
    ('tamten', 'actants', 'pl', 'that'),
    ('den där', 'actants', 'sv', 'that'),
    ('cela', 'actants', 'fr', 'that'),
    ('das', 'actants', 'de', 'that'),
    ('dat', 'actants', 'nl', 'that'),
    ('ja', 'actants', 'pl', 'I'),
    ('jag', 'actants', 'sv', 'I'),
    ('je', 'actants', 'fr', 'I'),
    ('ich', 'actants', 'de', 'I'),
    ('ik', 'actants', 'nl', 'I'),
    ('ty', 'actants', 'pl', 'you (informal)'),
    ('du', 'actants', 'sv', 'you (informal)'),
    ('tu', 'actants', 'fr', 'you (informal)'),
    ('du', 'actants', 'de', 'you (informal)'),
    ('jij', 'actants', 'nl', 'you (informal)'),
    ('on', 'actants', 'pl', 'he'),
    ('han', 'actants', 'sv', 'he'),
    ('il', 'actants', 'fr', 'he'),
    ('er', 'actants', 'de', 'he'),
    ('hij', 'actants', 'nl', 'he'),
    ('ona', 'actants', 'pl', 'she'),
    ('hon', 'actants', 'sv', 'she'),
    ('elle', 'actants', 'fr', 'she'),
    ('sie', 'actants', 'de', 'she'),
    ('zij', 'actants', 'nl', 'she'),
    ('to', 'actants', 'pl', 'it'),
    ('den', 'actants', 'sv', 'it'),
    ('il', 'actants', 'fr', 'it'),
    ('es', 'actants', 'de', 'it'),
    ('het', 'actants', 'nl', 'it'),
    ('kto', 'actants', 'pl', 'who'),
    ('vem', 'actants', 'sv', 'who'),
    ('qui', 'actants', 'fr', 'who'),
    ('wer', 'actants', 'de', 'who'),
    ('wie', 'actants', 'nl', 'who'),
    ('gdzie', 'relators', 'pl', 'where'),
    ('var', 'relators', 'sv', 'where'),
    ('où', 'relators', 'fr', 'where'),
    ('wo', 'relators', 'de', 'where'),
    ('waar', 'relators', 'nl', 'where'),
    ('kiedy', 'relators', 'pl', 'when'),
    ('när', 'relators', 'sv', 'when'),
    ('quand', 'relators', 'fr', 'when'),
    ('wann', 'relators', 'de', 'when'),
    ('wanneer', 'relators', 'nl', 'when'),
    ('co', 'actants', 'pl', 'what'),
    ('vad', 'actants', 'sv', 'what'),
    ('que', 'actants', 'fr', 'what'),
    ('was', 'actants', 'de', 'what'),
    ('wat', 'actants', 'nl', 'what'),
    ('dlaczego', 'operators', 'pl', 'why'),
    ('varför', 'operators', 'sv', 'why'),
    ('pourquoi', 'operators', 'fr', 'why'),
    ('warum', 'operators', 'de', 'why'),
    ('waarom', 'operators', 'nl', 'why'),
    ('jak', 'operators', 'pl', 'how'),
    ('hur', 'operators', 'sv', 'how'),
    ('comment', 'operators', 'fr', 'how'),
    ('wie', 'operators', 'de', 'how'),
    ('hoe', 'operators', 'nl', 'how'),
    ('pan/pani', 'actants', 'pl', 'you (formal)'),
    ('ni', 'actants', 'sv', 'you (formal)'),
    ('vous', 'actants', 'fr', 'you (formal)'),
    ('Sie', 'actants', 'de', 'you (formal)'),
    ('u', 'actants', 'nl', 'you (formal)'),
    ('duży', 'actions & states', 'pl', 'big'),
    ('stor', 'actions & states', 'sv', 'big'),
    ('grand', 'actions & states', 'fr', 'big'),
    ('groß', 'actions & states', 'de', 'big'),
    ('groot', 'actions & states', 'nl', 'big'),
    ('mały', 'actions & states', 'pl', 'small'),
    ('liten', 'actions & states', 'sv', 'small'),
    ('petit', 'actions & states', 'fr', 'small'),
    ('klein', 'actions & states', 'de', 'small'),
    ('klein', 'actions & states', 'nl', 'small'),
    ('dobry', 'actions & states', 'pl', 'good'),
    ('bra', 'actions & states', 'sv', 'good'),
    ('bon', 'actions & states', 'fr', 'good'),
    ('gut', 'actions & states', 'de', 'good'),
    ('goed', 'actions & states', 'nl', 'good'),
    ('zły', 'actions & states', 'pl', 'bad'),
    ('dålig', 'actions & states', 'sv', 'bad'),
    ('mauvais', 'actions & states', 'fr', 'bad'),
    ('schlecht', 'actions & states', 'de', 'bad'),
    ('slecht', 'actions & states', 'nl', 'bad'),
    ('szczęśliwy', 'actions & states', 'pl', 'happy'),
    ('glad', 'actions & states', 'sv', 'happy'),
    ('heureux', 'actions & states', 'fr', 'happy'),
    ('glücklich', 'actions & states', 'de', 'happy'),
    ('blij', 'actions & states', 'nl', 'happy'),
    ('smutny', 'actions & states', 'pl', 'sad'),
    ('ledsen', 'actions & states', 'sv', 'sad'),
    ('triste', 'actions & states', 'fr', 'sad'),
    ('traurig', 'actions & states', 'de', 'sad'),
    ('verdrietig', 'actions & states', 'nl', 'sad'),
    ('gorący', 'actions & states', 'pl', 'hot'),
    ('varm', 'actions & states', 'sv', 'hot'),
    ('chaud', 'actions & states', 'fr', 'hot'),
    ('heiß', 'actions & states', 'de', 'hot'),
    ('heet', 'actions & states', 'nl', 'hot'),
    ('zimny', 'actions & states', 'pl', 'cold'),
    ('kall', 'actions & states', 'sv', 'cold'),
    ('froid', 'actions & states', 'fr', 'cold'),
    ('kalt', 'actions & states', 'de', 'cold'),
    ('koud', 'actions & states', 'nl', 'cold'),
    ('czerwony', 'actions & states', 'pl', 'red'),
    ('röd', 'actions & states', 'sv', 'red'),
    ('rouge', 'actions & states', 'fr', 'red'),
    ('rot', 'actions & states', 'de', 'red'),
    ('rood', 'actions & states', 'nl', 'red'),
    ('niebieski', 'actions & states', 'pl', 'blue'),
    ('blå', 'actions & states', 'sv', 'blue'),
    ('bleu', 'actions & states', 'fr', 'blue'),
    ('blau', 'actions & states', 'de', 'blue'),
    ('blauw', 'actions & states', 'nl', 'blue'),
    ('prawy', 'actions & states', 'pl', 'right'),
    ('höger', 'actions & states', 'sv', 'right'),
    ('droit', 'actions & states', 'fr', 'right'),
    ('rechts', 'actions & states', 'de', 'right'),
    ('rechts', 'actions & states', 'nl', 'right'),
    ('lewy', 'actions & states', 'pl', 'left'),
    ('vänster', 'actions & states', 'sv', 'left'),
    ('gauche', 'actions & states', 'fr', 'left'),
    ('links', 'actions & states', 'de', 'left'),
    ('links', 'actions & states', 'nl', 'left'),
    ('słuszne', 'actions & states', 'pl', 'right ("correct")'),
    ('rätt', 'actions & states', 'sv', 'right ("correct")'),
    ('juste', 'actions & states', 'fr', 'right ("correct")'),
    ('richtig', 'actions & states', 'de', 'right ("correct")'),
    ('goed', 'actions & states', 'nl', 'right ("correct")'),
    ('niesłuszne', 'actions & states', 'pl', 'wrong'),
    ('fel', 'actions & states', 'sv', 'wrong'),
    ('faux', 'actions & states', 'fr', 'wrong'),
    ('falsch', 'actions & states', 'de', 'wrong'),
    ('fout', 'actions & states', 'nl', 'wrong'),
    ('prawda', 'actions & states', 'pl', 'TRUE'),
    ('sant', 'actions & states', 'sv', 'TRUE'),
    ('vrai', 'actions & states', 'fr', 'TRUE'),
    ('wahr', 'actions & states', 'de', 'TRUE'),
    ('waar', 'actions & states', 'nl', 'TRUE'),
    ('fałsz', 'actions & states', 'pl', 'FALSE'),
    ('falskt', 'actions & states', 'sv', 'FALSE'),
    ('faux', 'actions & states', 'fr', 'FALSE'),
    ('falsch', 'actions & states', 'de', 'FALSE'),
    ('onwaar', 'actions & states', 'nl', 'FALSE'),
    ('mężczyzna', 'actants', 'pl', 'man'),
    ('man', 'actants', 'sv', 'man'),
    ('homme', 'actants', 'fr', 'man'),
    ('Mann', 'actants', 'de', 'man'),
    ('man', 'actants', 'nl', 'man'),
    ('kobieta', 'actants', 'pl', 'woman'),
    ('kvinna', 'actants', 'sv', 'woman'),
    ('femme', 'actants', 'fr', 'woman'),
    ('Frau', 'actants', 'de', 'woman'),
    ('vrouw', 'actants', 'nl', 'woman'),
    ('duch', 'actants', 'pl', 'ghost'),
    ('spöke', 'actants', 'sv', 'ghost'),
    ('fantôme', 'actants', 'fr', 'ghost'),
    ('Geist', 'actants', 'de', 'ghost'),
    ('spook', 'actants', 'nl', 'ghost'),
    ('pies', 'actants', 'pl', 'dog'),
    ('hund', 'actants', 'sv', 'dog'),
    ('chien', 'actants', 'fr', 'dog'),
    ('Hund', 'actants', 'de', 'dog'),
    ('hond', 'actants', 'nl', 'dog'),
    ('przyjaciel', 'actants', 'pl', 'friend'),
    ('vän', 'actants', 'sv', 'friend'),
    ('ami', 'actants', 'fr', 'friend'),
    ('Freund', 'actants', 'de', 'friend'),
    ('vriend', 'actants', 'nl', 'friend'),
    ('dom', 'actants', 'pl', 'house'),
    ('hus', 'actants', 'sv', 'house'),
    ('maison', 'actants', 'fr', 'house'),
    ('Haus', 'actants', 'de', 'house'),
    ('huis', 'actants', 'nl', 'house'),
    ('łóżko', 'actants', 'pl', 'bed'),
    ('säng', 'actants', 'sv', 'bed'),
    ('lit', 'actants', 'fr', 'bed'),
    ('Bett', 'actants', 'de', 'bed'),
    ('bed', 'actants', 'nl', 'bed'),
    ('kamień', 'actants', 'pl', 'stone'),
    ('sten', 'actants', 'sv', 'stone'),
    ('pierre', 'actants', 'fr', 'stone'),
    ('Stein', 'actants', 'de', 'stone'),
    ('steen', 'actants', 'nl', 'stone'),
    ('niebo', 'actants', 'pl', 'sky'),
    ('himmel', 'actants', 'sv', 'sky'),
    ('ciel', 'actants', 'fr', 'sky'),
    ('Himmel', 'actants', 'de', 'sky'),
    ('lucht', 'actants', 'nl', 'sky'),
    ('woda', 'actants', 'pl', 'water'),
    ('vatten', 'actants', 'sv', 'water'),
    ('eau', 'actants', 'fr', 'water'),
    ('Wasser', 'actants', 'de', 'water'),
    ('water', 'actants', 'nl', 'water'),
    ('miłość', 'actants', 'pl', 'love'),
    ('kärlek', 'actants', 'sv', 'love'),
    ('amour', 'actants', 'fr', 'love'),
    ('Liebe', 'actants', 'de', 'love'),
    ('liefde', 'actants', 'nl', 'love'),
    ('czas', 'actants', 'pl', 'time'),
    ('tid', 'actants', 'sv', 'time'),
    ('temps', 'actants', 'fr', 'time'),
    ('Zeit', 'actants', 'de', 'time'),
    ('tijd', 'actants', 'nl', 'time'),
    ('sen', 'actants', 'pl', 'dream'),
    ('dröm', 'actants', 'sv', 'dream'),
    ('rêve', 'actants', 'fr', 'dream'),
    ('Traum', 'actants', 'de', 'dream'),
    ('droom', 'actants', 'nl', 'dream'),
    ('sekret', 'actants', 'pl', 'secret'),
    ('hemlighet', 'actants', 'sv', 'secret'),
    ('secret', 'actants', 'fr', 'secret'),
    ('Geheimnis', 'actants', 'de', 'secret'),
    ('geheim', 'actants', 'nl', 'secret'),
    ('śmierć', 'actants', 'pl', 'death'),
    ('död', 'actants', 'sv', 'death'),
    ('mort', 'actants', 'fr', 'death'),
    ('Tod', 'actants', 'de', 'death'),
    ('dood', 'actants', 'nl', 'death'),
    ('biegać', 'actions & states', 'pl', 'run'),
    ('springa', 'actions & states', 'sv', 'run'),
    ('courir', 'actions & states', 'fr', 'run'),
    ('rennen', 'actions & states', 'de', 'run'),
    ('rennen', 'actions & states', 'nl', 'run'),
    ('łamać', 'actions & states', 'pl', 'break'),
    ('bryta', 'actions & states', 'sv', 'break'),
    ('casser', 'actions & states', 'fr', 'break'),
    ('brechen', 'actions & states', 'de', 'break'),
    ('breken', 'actions & states', 'nl', 'break'),
    ('upadać', 'actions & states', 'pl', 'fall'),
    ('falla', 'actions & states', 'sv', 'fall'),
    ('tomber', 'actions & states', 'fr', 'fall'),
    ('fallen', 'actions & states', 'de', 'fall'),
    ('vallen', 'actions & states', 'nl', 'fall'),
    ('chować', 'actions & states', 'pl', 'hide'),
    ('gömma', 'actions & states', 'sv', 'hide'),
    ('cacher', 'actions & states', 'fr', 'hide'),
    ('verstecken', 'actions & states', 'de', 'hide'),
    ('verbergen', 'actions & states', 'nl', 'hide'),
    ('palić', 'actions & states', 'pl', 'burn'),
    ('brinna', 'actions & states', 'sv', 'burn'),
    ('brûler', 'actions & states', 'fr', 'burn'),
    ('brennen', 'actions & states', 'de', 'burn'),
    ('branden', 'actions & states', 'nl', 'burn'),
    ('ciemny', 'actions & states', 'pl', 'dark'),
    ('mörk', 'actions & states', 'sv', 'dark'),
    ('sombre', 'actions & states', 'fr', 'dark'),
    ('dunkel', 'actions & states', 'de', 'dark'),
    ('donker', 'actions & states', 'nl', 'dark'),
    ('słodki', 'actions & states', 'pl', 'sweet'),
    ('söt', 'actions & states', 'sv', 'sweet'),
    ('doux', 'actions & states', 'fr', 'sweet'),
    ('süß', 'actions & states', 'de', 'sweet'),
    ('zoet', 'actions & states', 'nl', 'sweet'),
    ('stary', 'actions & states', 'pl', 'old'),
    ('gammal', 'actions & states', 'sv', 'old'),
    ('vieux', 'actions & states', 'fr', 'old'),
    ('alt', 'actions & states', 'de', 'old'),
    ('oud', 'actions & states', 'nl', 'old'),
    ('chcieć', 'actions & states', 'pl', 'want'),
    ('vilja', 'actions & states', 'sv', 'want'),
    ('vouloir', 'actions & states', 'fr', 'want'),
    ('wollen', 'actions & states', 'de', 'want'),
    ('willen', 'actions & states', 'nl', 'want'),
    ('widzieć', 'actions & states', 'pl', 'see'),
    ('se', 'actions & states', 'sv', 'see'),
    ('voir', 'actions & states', 'fr', 'see'),
    ('sehen', 'actions & states', 'de', 'see'),
    ('zien', 'actions & states', 'nl', 'see'),
    ('słyszeć', 'actions & states', 'pl', 'hear'),
    ('höra', 'actions & states', 'sv', 'hear'),
    ('entendre', 'actions & states', 'fr', 'hear'),
    ('hören', 'actions & states', 'de', 'hear'),
    ('horen', 'actions & states', 'nl', 'hear'),
    ('bać się', 'actions & states', 'pl', 'fear'),
    ('frukta', 'actions & states', 'sv', 'fear'),
    ('craindre', 'actions & states', 'fr', 'fear'),
    ('fürchten', 'actions & states', 'de', 'fear'),
    ('vrezen', 'actions & states', 'nl', 'fear'),
    ('wiedzieć', 'actions & states', 'pl', 'know'),
    ('veta', 'actions & states', 'sv', 'know'),
    ('savoir', 'actions & states', 'fr', 'know'),
    ('wissen', 'actions & states', 'de', 'know'),
    ('weten', 'actions & states', 'nl', 'know'),
    ('blisko', 'relators', 'pl', 'near'),
    ('nära', 'relators', 'sv', 'near'),
    ('près de', 'relators', 'fr', 'near'),
    ('nah', 'relators', 'de', 'near'),
    ('dichtbij', 'relators', 'nl', 'near'),
    ('przez', 'relators', 'pl', 'through'),
    ('genom', 'relators', 'sv', 'through'),
    ('à travers', 'relators', 'fr', 'through'),
    ('durch', 'relators', 'de', 'through'),
    ('door', 'relators', 'nl', 'through'),
    ('przed', 'relators', 'pl', 'before'),
    ('före', 'relators', 'sv', 'before'),
    ('avant', 'relators', 'fr', 'before'),
    ('vor', 'relators', 'de', 'before'),
    ('voor', 'relators', 'nl', 'before'),
    ('po', 'relators', 'pl', 'after'),
    ('efter', 'relators', 'sv', 'after'),
    ('après', 'relators', 'fr', 'after'),
    ('nach', 'relators', 'de', 'after'),
    ('na', 'relators', 'nl', 'after'),
    ('teraz', 'relators', 'pl', 'now'),
    ('nu', 'relators', 'sv', 'now'),
    ('maintenant', 'relators', 'fr', 'now'),
    ('jetzt', 'relators', 'de', 'now'),
    ('nu', 'relators', 'nl', 'now'),
    ('wtedy', 'relators', 'pl', 'then'),
    ('då', 'relators', 'sv', 'then'),
    ('alors', 'relators', 'fr', 'then'),
    ('dann', 'relators', 'de', 'then'),
    ('dan', 'relators', 'nl', 'then'),
    ('nie', 'operators', 'pl', 'no'),
    ('nej', 'operators', 'sv', 'no'),
    ('non', 'operators', 'fr', 'no'),
    ('nein', 'operators', 'de', 'no'),
    ('nee', 'operators', 'nl', 'no'),
    ('nigdy', 'operators', 'pl', 'never'),
    ('aldrig', 'operators', 'sv', 'never'),
    ('jamais', 'operators', 'fr', 'never'),
    ('nie', 'operators', 'de', 'never'),
    ('nooit', 'operators', 'nl', 'never'),
    ('wszyscy', 'operators', 'pl', 'all'),
    ('alla', 'operators', 'sv', 'all'),
    ('tout', 'operators', 'fr', 'all'),
    ('alle', 'operators', 'de', 'all'),
    ('alle', 'operators', 'nl', 'all'),
    ('niektórzy', 'operators', 'pl', 'some'),
    ('några', 'operators', 'sv', 'some'),
    ('certains', 'operators', 'fr', 'some'),
    ('einige', 'operators', 'de', 'some'),
    ('sommige', 'operators', 'nl', 'some'),
    ('żaden', 'operators', 'pl', 'none'),
    ('ingen', 'operators', 'sv', 'none'),
    ('aucun', 'operators', 'fr', 'none'),
    ('keine', 'operators', 'de', 'none'),
    ('geen', 'operators', 'nl', 'none'),
    ('jeden', 'operators', 'pl', 'one'),
    ('en', 'operators', 'sv', 'one'),
    ('un', 'operators', 'fr', 'one'),
    ('eins', 'operators', 'de', 'one'),
    ('een', 'operators', 'nl', 'one'),
    ('wiele', 'operators', 'pl', 'many'),
    ('många', 'operators', 'sv', 'many'),
    ('beaucoup', 'operators', 'fr', 'many'),
    ('viele', 'operators', 'de', 'many'),
    ('veel', 'operators', 'nl', 'many'),
    ('bon', 'adjective', 'fr', 'good'),
    ('dobry', 'adjective', 'pl', 'good'),
    ('bra', 'adjective', 'sv', 'good'),
    ('gut', 'adjective', 'de', 'good'),
    ('goed', 'adjective', 'nl', 'good'),
    ('mauvais', 'adjective', 'fr', 'bad'),
    ('zły', 'adjective', 'pl', 'bad'),
    ('dålig', 'adjective', 'sv', 'bad'),
    ('schlecht', 'adjective', 'de', 'bad'),
    ('slecht', 'adjective', 'nl', 'bad'),
    ('situation', 'noun', 'fr', 'situation'),
    ('sytuacja', 'noun', 'pl', 'situation'),
    ('situation', 'noun', 'sv', 'situation'),
    ('Situation', 'noun', 'de', 'situation'),
    ('situatie', 'noun', 'nl', 'situation'),
    ('résumer', 'verb', 'fr', 'to summarize'),
    ('podsumować', 'verb', 'pl', 'to summarize'),
    ('sammanfatta', 'verb', 'sv', 'to summarize'),
    ('zusammenfassen', 'verb', 'de', 'to summarize'),
    ('samenvatten', 'verb', 'nl', 'to summarize'),
    ('vie', 'noun', 'fr', 'life'),
    ('życie', 'noun', 'pl', 'life'),
    ('liv', 'noun', 'sv', 'life'),
    ('Leben', 'noun', 'de', 'life'),
    ('leven', 'noun', 'nl', 'life'),
    ('aujourd\'hui', 'adverb', 'fr', 'today'),
    ('dzisiaj', 'adverb', 'pl', 'today'),
    ('idag', 'adverb', 'sv', 'today'),
    ('heute', 'adverb', 'de', 'today'),
    ('vandaag', 'adverb', 'nl', 'today'),
    ('rencontre', 'noun', 'fr', 'encounter'),
    ('spotkanie', 'noun', 'pl', 'encounter'),
    ('möte', 'noun', 'sv', 'encounter'),
    ('Begegnung', 'noun', 'de', 'encounter'),
    ('ontmoeting', 'noun', 'nl', 'encounter'),
    ('personne', 'noun', 'fr', 'person'),
    ('człowiek', 'noun', 'pl', 'person'),
    ('människa', 'noun', 'sv', 'person'),
    ('Mensch', 'noun', 'de', 'person'),
    ('mens', 'noun', 'nl', 'person'),
    ('tendre', 'verb', 'fr', 'to extend'),
    ('wyciągnąć', 'verb', 'pl', 'to extend'),
    ('sträcka', 'verb', 'sv', 'to extend'),
    ('ausstrecken', 'verb', 'de', 'to extend'),
    ('uitstrekken', 'verb', 'nl', 'to extend'),
    ('main', 'noun', 'fr', 'hand'),
    ('dłoń', 'noun', 'pl', 'hand'),
    ('hand', 'noun', 'sv', 'hand'),
    ('Hand', 'noun', 'de', 'hand'),
    ('hand', 'noun', 'nl', 'hand'),
    ('moment', 'noun', 'fr', 'moment'),
    ('moment', 'noun', 'pl', 'moment'),
    ('tidpunkt', 'noun', 'sv', 'moment'),
    ('Moment', 'noun', 'de', 'moment'),
    ('moment', 'noun', 'nl', 'moment'),
    ('seul', 'adjective', 'fr', 'alone'),
    ('sam', 'adjective', 'pl', 'alone'),
    ('ensam', 'adjective', 'sv', 'alone'),
    ('allein', 'adjective', 'de', 'alone'),
    ('alleen', 'adjective', 'nl', 'alone'),
    ('curieux', 'adjective', 'fr', 'curious'),
    ('ciekawy', 'adjective', 'pl', 'curious'),
    ('märklig', 'adjective', 'sv', 'curious'),
    ('neugierig', 'adjective', 'de', 'curious'),
    ('nieuwsgierig', 'adjective', 'nl', 'curious'),
    ('hasard', 'noun', 'fr', 'chance'),
    ('przypadek', 'noun', 'pl', 'chance'),
    ('slump', 'noun', 'sv', 'chance'),
    ('Zufall', 'noun', 'de', 'chance'),
    ('toeval', 'noun', 'nl', 'chance'),
    ('forger', 'verb', 'fr', 'to forge'),
    ('kształtować', 'verb', 'pl', 'to forge'),
    ('forma', 'verb', 'sv', 'to forge'),
    ('schmieden', 'verb', 'de', 'to forge'),
    ('smeden', 'verb', 'nl', 'to forge'),
    ('destinée', 'noun', 'fr', 'destiny'),
    ('przeznaczenie', 'noun', 'pl', 'destiny'),
    ('öde', 'noun', 'sv', 'destiny'),
    ('Schicksal', 'noun', 'de', 'destiny'),
    ('lot', 'noun', 'nl', 'destiny'),
    ('goût', 'noun', 'fr', 'taste'),
    ('smak', 'noun', 'pl', 'taste'),
    ('smak', 'noun', 'sv', 'taste'),
    ('Geschmack', 'noun', 'de', 'taste'),
    ('smaak', 'noun', 'nl', 'taste'),
    ('geste', 'noun', 'fr', 'gesture'),
    ('gest', 'noun', 'pl', 'gesture'),
    ('gest', 'noun', 'sv', 'gesture'),
    ('Geste', 'noun', 'de', 'gesture'),
    ('gebaar', 'noun', 'nl', 'gesture'),
    ('interlocuteur', 'noun', 'fr', 'interlocutor'),
    ('rozmówca', 'noun', 'pl', 'interlocutor'),
    ('samtalspartner', 'noun', 'sv', 'interlocutor'),
    ('Gesprächspartner', 'noun', 'de', 'interlocutor'),
    ('gesprekspartner', 'noun', 'nl', 'interlocutor'),
    ('miroir', 'noun', 'fr', 'mirror'),
    ('lustro', 'noun', 'pl', 'mirror'),
    ('spegel', 'noun', 'sv', 'mirror'),
    ('Spiegel', 'noun', 'de', 'mirror'),
    ('spiegel', 'noun', 'nl', 'mirror'),
    ('avancer', 'verb', 'fr', 'to advance'),
    ('posuwać się naprzód', 'verb', 'pl', 'to advance'),
    ('gå framåt', 'verb', 'sv', 'to advance'),
    ('vorankommen', 'verb', 'de', 'to advance'),
    ('vooruitgaan', 'verb', 'nl', 'to advance'),
    ('amour', 'noun', 'fr', 'love'),
    ('miłość', 'noun', 'pl', 'love'),
    ('kärlek', 'noun', 'sv', 'love'),
    ('Liebe', 'noun', 'de', 'love'),
    ('liefde', 'noun', 'nl', 'love'),
]

PRONOUN_TRANSLATIONS = [
    'I', 'he', 'her', 'him', 'his', 'it', 'me', 'my', 'our', 'she', 'that',
    'their', 'them', 'they', 'this', 'us', 'we', 'what', 'who',
    'you (formal)', 'you (informal)', 'your',
]


def delete_spanish_words(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.filter(language='es').delete()


def noop(apps, schema_editor):
    pass


def seed_base_vocabulary(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    for text, category, language, translation in VOCABULARY:
        exists = Word.objects.filter(
            text=text, category=category, language=language, translation=translation,
        ).exists()
        if not exists:
            Word.objects.create(
                text=text, category=category, language=language, translation=translation,
            )


def unseed_base_vocabulary(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    for text, category, language, translation in VOCABULARY:
        Word.objects.filter(
            text=text, category=category, language=language, translation=translation,
        ).delete()


def recategorize_pronouns(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.filter(category='actants', translation__in=PRONOUN_TRANSLATIONS).update(
        category='pronoun'
    )


def revert_pronouns(apps, schema_editor):
    Word = apps.get_model('words', 'Word')
    Word.objects.filter(category='pronoun', translation__in=PRONOUN_TRANSLATIONS).update(
        category='actants'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_seed_word_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('sv', 'Swedish'), ('nl', 'Dutch')], max_length=10),
        ),
        migrations.RunPython(delete_spanish_words, noop),
        migrations.RunPython(seed_base_vocabulary, unseed_base_vocabulary),
        migrations.RunPython(recategorize_pronouns, revert_pronouns),
    ]
