# Generated by Django 5.2.16 on 2026-07-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_seed_word_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pl', 'Polish'), ('sv', 'Swedish'), ('nl', 'Dutch')], max_length=10),
        ),
    ]
