# Generated by Django 5.2.16 on 2026-07-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_remap_legacy_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('article', 'Article'), ('adjective', 'Adjective'), ('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('prefix', 'Prefix'), ('suffix', 'Suffix'), ('other', 'Other')], max_length=20),
        ),
    ]
